version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  labels: 
    - 'dependencies'
  open-pull-requests-limit: 3
  assignees:
    - "yasanglass"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  labels: 
    - 'ci'
    - 'dependencies'
  open-pull-requests-limit: 3
  assignees:
    - "yasanglass"